name: 'Run Salesforce Code Analyzer'
description:
  'Scans your code for violations using Salesforce Code Analyzer, uploads results as an artifact, and creates a job
  summary.'
author: 'Salesforce Code Analyzer Team'

branding:
  icon: 'play'
  color: 'gray-dark'

inputs:
  run-arguments:
    description: |-
      Specifies arguments passed to the `run` command.
      Default: "--view detail --output-file sfca_results.json"

      For a full list of acceptable arguments for the run command, see the [code-analyzer Command Reference](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_code-analyzer_commands_unified.htm).

      The stdout text from the `run` command is written to the GitHub workflow run logs.

      Each output file specified by a `--output-file` (or `-f`) flag is included in the zip archive GitHub workflow run artifact for you to download.
    required: false
    default: '--view detail --output-file sfca_results.json'
  results-artifact-name:
    description: |-
      Specifies the name of the zip archive GitHub workflow run artifact where the results output file is uploaded.
      Default: "salesforce-code-analyzer-results"
    required: false
    default: 'salesforce-code-analyzer-results'

outputs:
  exit-code:
    description: The Salesforce Code Analyzer execution exit code.
  num-violations:
    description: The total number of violations found.
  num-sev1-violations:
    description: The number of Critical (1) severity violations found.
  num-sev2-violations:
    description: The number of High (2) severity violations found.
  num-sev3-violations:
    description: The number of Medium (3) severity violations found.
  num-sev4-violations:
    description: The number of Low (4) severity violations found.
  num-sev5-violations:
    description: The number of Info (5) severity violations found.

runs:
  using: node20
  main: dist/index.js
